name: Update Currency Data

on:
  schedule:
    - cron: '0 19 * * *'  # This runs the workflow every day at UTC time

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version:  '3.10.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Python script
        run: python price.py

      - name: Commit and push changes
        run: |
          git add price.js
          git commit -m "Update Currency Data"
          git push

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main 
